### ISSUE TITLE
Rake error - ArgumentError: unknown keyword: start

### ISSUE THREAD

**Issue by ethan-gaudet** [ginjo/rfm#46]
Using ginjo-rfm 3.0.12 seems to break Rake on Rails 5.1.1. Whenever I try to run any rake task I get the following error:

ArgumentError: unknown keyword: start
/home/user/.rvm/gems/ruby-2.4.1@rails_project/gems/activesupport-5.1.7/lib/active_support/core_ext/module/delegation.rb:155:in `delegate'
/home/user/.rvm/gems/ruby-2.4.1@rails_project/gems/listen-3.1.5/lib/listen/backend.rb:29:in `<class:Backend>'
/home/user/.rvm/gems/ruby-2.4.1@rails_project/gems/listen-3.1.5/lib/listen/backend.rb:10:in `<module:Listen>'
/home/user/.rvm/gems/ruby-2.4.1@rails_project/gems/listen-3.1.5/lib/listen/backend.rb:9:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.4.1@rails_project/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `require'
/home/user/.rvm/gems/ruby-2.4.1@rails_project/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `block in require'
/home/user/.rvm/gems/ruby-2.4.1@rails_project/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/user/.rvm/gems/ruby-2.4.1@rails_project/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `require'
/home/user/.rvm/gems/ruby-2.4.1@rails_project/gems/listen-3.1.5/lib/listen/listener.rb:5:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.4.1@rails_project/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `require'
/home/user/.rvm/gems/ruby-2.4.1@rails_project/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `block in require'
/home/user/.rvm/gems/ruby-2.4.1@rails_project/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/user/.rvm/gems/ruby-2.4.1@rails_project/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `require'
/home/user/.rvm/gems/ruby-2.4.1@rails_project/gems/listen-3.1.5/lib/listen.rb:3:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.4.1@rails_project/gems/bundler-2.0.1/lib/bundler/runtime.rb:81:in `require'
/home/user/.rvm/gems/ruby-2.4.1@rails_project/gems/bundler-2.0.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/home/user/.rvm/gems/ruby-2.4.1@rails_project/gems/bundler-2.0.1/lib/bundler/runtime.rb:76:in `each'
/home/user/.rvm/gems/ruby-2.4.1@rails_project/gems/bundler-2.0.1/lib/bundler/runtime.rb:76:in `block in require'
/home/user/.rvm/gems/ruby-2.4.1@rails_project/gems/bundler-2.0.1/lib/bundler/runtime.rb:65:in `each'
/home/user/.rvm/gems/ruby-2.4.1@rails_project/gems/bundler-2.0.1/lib/bundler/runtime.rb:65:in `require'
/home/user/.rvm/gems/ruby-2.4.1@rails_project/gems/bundler-2.0.1/lib/bundler.rb:114:in `require'
/home/user/rails/rails_project/config/application.rb:7:in `<top (required)>'
/home/user/rails/rails_project/Rakefile:4:in `require_relative'
/home/user/rails/rails_project/Rakefile:4:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.4.1@rails_project/bin/ruby_executable_hooks:24:in `eval'
/home/user/.rvm/gems/ruby-2.4.1@rails_project/bin/ruby_executable_hooks:24:in `<main>'

When I remove the ginjo-rfm gem, Rake works as normal. I tried downgrading the gem to no avail.

**Comment by ethan-gaudet** [comment]
Just to add to this - I tried using ginjo-rfm on a bare-bones Rails 5.2.3 install, and Rake throws the same error.
